# Generated by Django 4.2.6 on 2024-01-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='reader_address',
            field=models.TextField(default='Accra'),
        ),
    ]
